# Generated by Django 4.1.4 on 2022-12-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id_raw", models.CharField(max_length=32)),
                ("transaction_id", models.CharField(max_length=32, unique=True)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=12)),
                ("date", models.DateField()),
            ],
        ),
    ]
