# Generated by Django 5.2.5 on 2025-10-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("natural_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
