# Generated by Django 5.2.5 on 2025-09-20 16:07

from django.db import migrations


def forward(apps, schema_editor):
    CampaignBDSIsrael = apps.get_model("market_data", "CampaignBDSIsrael")
    values = [
        CampaignBDSIsrael(
            natural_id="BDSHigh",
            name="BDS High Priority",
            is_default=False,
        ),
        CampaignBDSIsrael(
            natural_id="BDSMedium",
            name="BDS Medium Priority",
            is_default=False,
        ),
        CampaignBDSIsrael(
            natural_id="BDSLow",
            name="BDS Low Priority",
            is_default=False,
        ),
        CampaignBDSIsrael(
            natural_id="BDSNoBoycott",
            name="BDS No Boycott",
            is_default=True,
        ),
    ]
    CampaignBDSIsrael.objects.bulk_create(values)


def backward(apps, schema_editor):
    CampaignBDSIsrael = apps.get_model("market_data", "CampaignBDSIsrael")
    CampaignBDSIsrael.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
