# Generated by Django 5.2.5 on 2025-09-20 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("householdentities", "0001_initial"),
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "metric",
                    models.CharField(
                        choices=[("Spending", "Spending")], max_length=100
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_values",
                        to="householdentities.account",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market_data.vendor",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "account", "vendor", "metric"),
                        name="uniq_metric_val",
                    )
                ],
            },
        ),
    ]
