# Generated by Django 5.2.5 on 2025-09-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricvalue",
            name="value",
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
    ]
