# Generated by Django 5.2.5 on 2025-08-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id_raw", models.CharField(max_length=32)),
                ("transaction_id", models.CharField(max_length=32, unique=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="transactions",
                        to="householdentities.account",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=12)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
