# Generated by Django 4.1.4 on 2023-01-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Unique name of the account')),
                ('institution', models.CharField(choices=[('td_canada', 'TD_CANADA'), ('koho', 'KOHO')], max_length=50)),
            ],
        ),
    ]
