# Generated by Django 4.1.4 on 2023-01-05 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='inception_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 2, 7, 20, 772161, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
