# Generated by Django 5.2.5 on 2025-10-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorTransactionIdMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id_raw", models.CharField(max_length=100)),
                ("vendor_id", models.CharField(max_length=100)),
            ],
        ),
    ]
