# Generated by Django 5.2.5 on 2025-10-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importing", "0002_vendortransactionidmap"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="vendortransactionidmap",
            constraint=models.UniqueConstraint(
                fields=("transaction_id_raw", "vendor_id"),
                name="uniq_vendor_trx_id_map",
            ),
        ),
    ]
