# Generated by Django 5.2.5 on 2025-10-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importing", "0003_vendortransactionidmap_uniq_vendor_trx_id_map"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vendortransactionidmap",
            name="uniq_vendor_trx_id_map",
        ),
        migrations.AddConstraint(
            model_name="vendortransactionidmap",
            constraint=models.UniqueConstraint(
                models.F("transaction_id_raw"),
                models.F("vendor_id"),
                name="uniq_vendor_trx_id_map",
            ),
        ),
    ]
