# Generated by Django 5.2.5 on 2025-09-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("natural_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "institution",
                    models.CharField(
                        choices=[("td_canada", "TDCanada"), ("koho", "KOHO")],
                        max_length=16,
                    ),
                ),
                (
                    "balance_initial",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("date_start", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
